name: emt7any
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Debug
  flutter_native_splash: ^2.4.6

  # Controllers
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.5
  hydrated_bloc: ^10.1.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

  # Helper
  dio: ^5.9.0
  intl: ^0.20.2
  get_it: ^8.2.0
  video_player: ^2.10.0
  fluttertoast: ^8.2.12
  flutter_dotenv: ^6.0.0
  flutter_screen_recording: ^2.0.24
  
  # UI
  shimmer: ^3.0.0
  qr_flutter: ^4.1.0
  awesome_dialog: ^3.2.1
  cupertino_icons: ^1.0.8

  # Database
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_utils: ^2.8.12
  flutter_lints: ^5.0.0

dependency_overrides:
  js: ^0.6.3
  flutter_secure_storage_web: any
  flutter_screen_recording_web: any

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/

flutter_assets:
  assets_path:
    - assets/images/
  output_path: lib/core/constants/
  filename: assets_manager.dart
  classname: AssetsManager

flutter_intl:
  enabled: true
  arb_dir: lib/core/localization/l10n
  output_dir: lib/core/localization/generated
